name: Android Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: "recursive"

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: temurin

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r27c
          link-to-sdk: true

      - name: Grant Execute Permission to gradlew
        run: chmod +x ./gradlew

      - name: Build Debug and Unsigned Release APKs
        run: ./gradlew assembleDebug assembleRelease --stacktrace

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: LeviLauncher-debug-apk
          path: app/build/outputs/apk/debug/*.apk

      - name: Upload Unsigned Release APK
        uses: actions/upload-artifact@v4
        with:
          name: LeviLauncher-release-unsigned-apk
          path: app/build/outputs/apk/release/*-unsigned.apk
